config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:index, :show, :edit, :update] do
    resources :matches, only: [:index, :show, :create, :edit, :update] do
      resources :messages, only: :create
    end
  end
  resources :matches, only: [:index, :destroy] do
    member do
      get :accept
    end
  end
  resources :messages, only: :destroy
  resources :searches, only: [:new]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <i class="fab fa-affiliatetheme"></i>
    <% if current_user %>
      <%= current_user.name %>
    <% end %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Profile", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", user_matches_path(current_user.id), class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "New match", new_search_path, class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_notification.html.erb
<%= link_to matches_path(match: @match.id), data: {turbolinks: :false} do %>
  <!-- <div class="notification container shadow p-3 m-3"> -->
  <div class="notification">
    <div class="row">
      <div class="col-6">
        <div class="personal-info">
          <% if current_user %>
            <% if @match.sender.avatar.attached? %>
              <%= cl_image_tag(@match.sender.avatar.key, class: "splash-profile-pic") %>
            <% else %>
              <img src="https://education.uky.edu/wp-content/uploads/2019/12/TL-Headshot-2squaresmall.jpg" alt="Profile-picture" class="splash-profile-pic">
            <% end %>
          <% end %>
          <div class="user-details">
            <p class="username" id="username" data-id="<%= current_user.id %>" style="font-family: 'Nunito Sans';font-weight: 600;padding-bottom: 1vh;color:rgb(94,94,144)">
              <% if current_user %>
                <%= @match.sender.name %>
              <% end %>
            </p>
            <p class="little-title" style="font-family: 'Nunito Sans';font-weight: 900;font-size:7px;opacity:0.6;">SKILL POINTS</p>
            <p class="skill-values" style="font-family: 'Nunito Sans';font-weight: 600;">
              <% if current_user %>
                <%= @match.sender.skill_rating %>
              <% end %>
            </p>
          </div>
          <i class="fas fa-medal" style="padding-top:2%;padding-left:3%;color:#cc6633;"></i>
        </div>
      </div>

      <div class="col-6">
          <p>You've been challenged to a match by <%= @match.sender.name %>!</p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="firstcolumn-wrapper container" style="overflow-y:scroll;max-height:100vh;">

  <div class="ourlogo" style="display: flow-root;">
    <%= image_tag "real_logo.png" %>
  </div>

  <div class="personal-info">
    <% if current_user %>
      <% if current_user.avatar.attached? %>
        <%= cl_image_tag(current_user.avatar.key, class: "splash-profile-pic") %>
      <% else %>
        <img src="https://education.uky.edu/wp-content/uploads/2019/12/TL-Headshot-2squaresmall.jpg" alt="Profile-picture" class="splash-profile-pic">
      <% end %>
    <% end %>
    <div class="user-details">
      <p class="username" id="username" data-id="<%= current_user.id %>" style="font-family: 'Nunito Sans';font-weight: 600;padding-bottom: 1vh;color:rgb(94,94,144)">
        <% if current_user %>
          <%= current_user.name %>
        <% end %>
      </p>
      <p class="little-title" style="font-family: 'Nunito Sans';font-weight: 900;font-size:7px;opacity:0.6;">SKILL POINTS</p>
      <p class="skill-values" style="font-family: 'Nunito Sans';font-weight: 600;">
        <% if current_user %>
          <%= current_user.skill_rating %>
        <% end %>
      </p>
    </div>
    <i class="fas fa-medal" style="padding-top:2%;padding-left:3%;color:#cc6633;"></i>
  </div>

  <div class="navbarlist">
    <ul>
      <li class="nav-link link-btn home-button" id="home-butto-padding"><%= link_to "Home", "/" %></li><hr>
      <% if current_user %>
        <li class="nav-link link-btn"><button type="button" class="profile-modal-button" data-toggle="modal" data-target="#exampleModalScrollable" style="outline:none;">
          Profile
        </button></li><hr>
        <li class="nav-link link-btn"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li><hr>

        <li class="nav-link match-button" type="button" data-toggle="modal" data-target=".bd-example-modal-lg">New Match</li>
      <% else %>
        <li class="nav-link link-btn"><%= link_to "Login", new_user_session_path %></li><hr>
      <% end %>
    </ul>

    <!-- <div class="navbar-card-container"> -->

      <% if current_user %>
        <% current_user.sort_matches.each do |match| %>
          <% sender = match.sender %>
          <% receiver = match.receiver %>


          <div class="navbar-players-mini-card">

            <div class="navbar-mini-card-avatar">
              <% if sender.id == current_user.id %>
                <% if receiver.avatar.attached? %>
                  <%= link_to matches_path(match: match.id), data: {turbolinks: :false} do %>
                   <%= cl_image_tag(receiver.avatar.key, class:"navbar-mini-card-avatar") %>
                  <%end%>
                <% else %>
                  <%= link_to matches_path(match: match.id), data: {turbolinks: :false} do %>
                    <img src="https://pngimage.net/wp-content/uploads/2018/06/no-avatar-png-8.png" alt="avatar" class="navbar-mini-card-avatar">
                  <% end %>
                <% end %>
                <hr>
              <% end %>

              <% if receiver.id == current_user.id %>
                <% if sender.avatar.attached? %>
                  <%= link_to matches_path(match: match.id), data: {turbolinks: :false} do %>
                    <%=cl_image_tag(sender.avatar.key, class:"navbar-mini-card-avatar") %>
                  <%end%>
                <% else %>
                  <%= link_to matches_path(match: match.id), data: {turbolinks: :false} do %>
                    <img src="https://pngimage.net/wp-content/uploads/2018/06/no-avatar-png-8.png" alt="avatar" class="navbar-mini-card-avatar">
                  <% end %>
                <% end %>
                <hr>
              <% end %>
            </div>

            <div class="navbar-players-short-description">
              <% if current_user.id == receiver.id %>
                <% opponent = sender %>
              <% else %>
                <% opponent = receiver %>
              <% end %>
              <h2 style="font-family: 'Nunito Sans';font-weight: 600;padding-bottom: 1%;"><strong style="color: #616292;"><%= opponent.name.split(" ")[0] %></strong> <%= opponent.name.split(" ")[1]%></h2>
              <hr>
              <div class="navbar-available-date">
                <div class="navbar-skill-div">
                  <p class="navbar-skill-availability" style="font-family: 'Nunito Sans';font-weight: 900;opacity:0.6;"><%= match.start_datetime.strftime("%A %d/%m") %></p>
                  <p class="navbar-skill-values" style="font-family: 'Nunito Sans';font-weight: 600;"><%= match.start_datetime.strftime("%H:%M") %></p>
                </div>
              </div>
            </div>

            <div class="navbar-chat-icon" style="background: <%= match.get_property(current_user, :bg) %>;">
              <i class="<%= match.get_property(current_user, :icon) %>"></i>
              <!-- <i class="far fa-comment-dots"></i> -->
            </div>

          </div>

        <% end %>
      <% end %>

    <!-- </div> -->
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Profile</h5>
        <div>
          <i style="padding-left:12px;"class="fas fa-pencil-alt"></i>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <div class="row">
          <div class="col-6" style="border-right: solid 1px rgba(0,0,0,0.8)">
            <div class="personal-info">
              <% if current_user %>
                <% if current_user.avatar.attached? %>
                  <%= cl_image_tag(current_user.avatar.key, class: "splash-profile-pic") %>
                <% else %>
                  <img src="https://education.uky.edu/wp-content/uploads/2019/12/TL-Headshot-2squaresmall.jpg" alt="Profile-picture" class="splash-profile-pic">
                <% end %>
              <% end %>
              <div class="user-details">
                <p class="username" style="font-family: 'Nunito Sans';font-weight: 600;padding-bottom: 1vh;color:rgb(94,94,144)">
                  <% if current_user %>
                    <%= current_user.name %>
                  <% end %>
                </p>
                <p class="little-title" style="font-family: 'Nunito Sans';font-weight: 900;font-size:7px;opacity:0.6;">SKILL POINTS</p>
                <p class="skill-values" style="font-family: 'Nunito Sans';font-weight: 600;">
                  <% if current_user %>
                    <%= current_user.skill_rating %>
                  <% end %>
                </p>
              </div>
              <i class="fas fa-medal" style="padding-top:1%;padding-left:2%;color:#cc6633;"></i>
            </div>
            <div class="user-bio">
              <h5 style="margin-top:10px;margin-bottom:0;font-family: 'Nunito Sans';font-weight: 600;padding-bottom: 1vh;color:rgb(94,94,144)">Bio</h5>
                <%= current_user&.bio %>
            </div>
          </div>

          <div class="col-6">
            <div class="flexy">
              <img src="https://image.flaticon.com/icons/svg/669/669442.svg" alt="" style="height:20px;padding-right:7px;">
              <h5 style="font-family: 'Nunito Sans';font-weight: 600;color:rgb(94,94,144)">Player Stats</h5>
            </div>
            <div class="flexy">
              <div class="stats-item">
                <p style="font-family: 'Nunito Sans';font-weight: 900;font-size:12px;opacity:0.6;">MP</p>
                <p style="font-family: 'Nunito Sans';font-weight: 600;">11</p>
              </div>

              <div class="stats-item">
                <p style="font-family: 'Nunito Sans';font-weight: 900;font-size:12px;opacity:0.6;">W</p>
                <p style="font-family: 'Nunito Sans';font-weight: 600;">8</p>
              </div>

              <div class="stats-item">
                <p style="font-family: 'Nunito Sans';font-weight: 900;font-size:12px;opacity:0.6;">L</p>
                <p style="font-family: 'Nunito Sans';font-weight: 600;">3</p>
              </div>
            </div>
            <div class="cabinet-wrap">
              <h5 style="font-family: 'Nunito Sans';font-weight: 600;color:rgb(94,94,144)">Cabinet</h5>
              <div class="medals" style="display: flex;">
                <img src="https://image.flaticon.com/icons/svg/625/625396.svg" class="tropy-item my-tooltip">
                <span class="my-tooltiptext">3rd place</span>

                <img src="https://image.flaticon.com/icons/svg/744/744960.svg" class="tropy-item hip-tooltip">
                <span class="hip-tooltiptext">5 straight wins</span>
              </div>
            </div>
          </div>

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<% if current_user %>
  <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="form-container" style="max-height: 70%;">
          <div class="form-title ">
            <h2>Match search</h2>
          </div>
          <div class="form-container-box">
            <%= simple_form_for Search.new, url: users_path, method: :get, html: { class: "matching-form" }   do |f| %>
                <%= f.input :start_datetime, as: :date, html5: true, class: "pink-border", label: "When do you want to play?", input_html: { value: Date.today } %>
                <%= f.input :start_time, label: "Between:", default: Time.parse('18:00') %>
                <%= f.input :end_time, label: "and:", default: Time.parse('20:00')  %>
                <%= f.input :acceptance_deadline_hrs, label: "How many hours in advance must the opponent accept?", input_html: {value: f.object.acceptance_deadline_hrs || '8'}  %>
                <%= f.input :will_travel_km, label: "How far can you travel (km)?", input_html: {value: f.object.will_travel_km || current_user.will_travel_km}  %>
                <%#= text_field_tag(:match_address) %>
                <%= f.submit "Search!", class: "btn btn-primary btn-lg btn-block match-submit-button" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>