config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:index, :show, :edit, :update] do
    resources :matches, only: [:index, :show, :create, :edit, :update] do
      resources :messages, only: :create
    end
  end
  resources :matches, only: [:index, :destroy] do
    member do
      get :accept
    end
  end
  resources :messages, only: :destroy
  resources :searches, only: [:new]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: :sender_id
  belongs_to :receiver, class_name: 'User', foreign_key: :receiver_id
  belongs_to :venue
  has_many :messages

  PROPERTIES = {
    completed: {
      bg: "rgba(0,0,0,0.2)",
      icon: "far fa-check-square"
    },
    upcoming: {
      bg: "#EA5A07",
      icon: "fas fa-calendar-alt"
    },
    challenge: {
      bg: "#EACC06",
      icon: "fas fa-exclamation"
    },
    pending: {
      bg: "#EACC06",
      icon: "fas fa-hourglass-half"
    }
  }

  def get_property(current_user, key)

    if is_complete
      return PROPERTIES[:completed][key]
    elsif is_accepted
      return PROPERTIES[:upcoming][key]
    elsif current_user.id == receiver_id
      return PROPERTIES[:challenge][key]
    else
      return PROPERTIES[:pending][key]
    end

  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all
    @users = User.all
    if params[:match]
      @match = Match.find(params[:match])
    else
      @match = Match.all.first
    end
    @message = Message.new
  end

  def show
    @match = Match.find(params[:id])
    @message = Message.new
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      # broadcast to @match.receiver
      # data is the partial, manipulated in DOM by JS on the other end

      NotificationsChannel.broadcast_to(@match.receiver, render_to_string(partial: 'shared/notification'))
      redirect_to root_path
    else
      render "create"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def accept
    @match = Match.find(params[:id])
    @match.is_accepted = true
    @match.save
    redirect_to matches_path(match: @match.id)
  end

  private

  def match_params
    params.require(:match).permit(:acceptance_deadline_hrs, :start_datetime, :receiver_id, :sender_id, :venue_id, :content)
  end
end

app/views/matches/_challenge.html.erb
<div class="challenge-box">

  <% if current_user.id == @match.receiver_id %>
    <% opponent = @match.sender %>
  <% else %>
    <% opponent = @match.receiver %>
  <% end %>

  <% if @match.is_accepted %>
    <h3>Upcoming match</h3>
  <% elsif current_user.id == @match.receiver_id %>
    <h3>You've been challenged!</h3>
  <% else %>
    <h3>Pending challenge</h3>
  <% end %>

  <% if !@match.is_accepted && current_user.id == @match.receiver_id %>
    <div class="challenge-buttons" style="height: 30px;">
      <!-- button: accept -->
      <%= link_to "Accept", accept_match_path(@match), class: "accept-button" %>
      <!-- button: reject -->
      <%= link_to "Reject", root_path, class: "rejecter" %>
    </div>
  <% end %>

  <div>
    <div class="challenge-info">
      <!-- datetime -->
      <p><em>Date and time:</em></p>
      <p><strong><%= @match.start_datetime.strftime("%A %d/%m, %H:%M") %></strong></p>
      <br>

      <% if !@match.is_accepted %>
        <!-- acceptance deadline -->
        <% deadline = (@match.start_datetime - @match.acceptance_deadline_hrs * 3600) %>
        <p><em>Acceptance deadline:</em></p>
        <p><strong><%= deadline.strftime("%A %d/%m, %H:%M") %></strong></p>
        <br>
      <% end %>

      <!-- msg/content -->
      <% if current_user.id == @match.receiver_id %>
        <p><em>Their message:</em></p>
      <% else %>
        <p><em>Your message:</em></p>
      <% end %>
      <p><%= @match.content %></p>
      <br>

      <p><em>Skill points risked:</em></p>
      <% points = current_user.skillpoints_risked(opponent) %>
      <p class="points-risk"><span class="win">+<%= points[:gained] %></span> / <span class="lose">-<%= points[:lost] %></span></p>

    </div>
    <!-- venue w/ map -->
    <div class="challenge-location">
      <p><em>Location:</em></p>
      <div class="map" id="map_0"
       style="width: 250px;
       height: 250px;"
       data-markers="<%= [{
                            lat: opponent.latitude,
                            lng: opponent.longitude,
                            cl_image_url: opponent.avatar.key
                           }, {
                            lat: current_user.latitude,
                            lng: current_user.longitude
                           }].to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/matches/create.html.erb
<h1>Matches#create</h1>
<p>Find me in app/views/matches/create.html.erb</p>

app/views/matches/destroy.html.erb
<h1>Matches#destroy</h1>
<p>Find me in app/views/matches/destroy.html.erb</p>

app/views/matches/edit.html.erb
<h1>Matches#edit</h1>
<p>Find me in app/views/matches/edit.html.erb</p>

app/views/matches/index.html.erb
<div class="row little-margin" style="background-color:white">
  <div class="col-3 first-row">
      <%= render 'shared/sidebar' %>
  </div>


  <div class="col-6 contents-div" style="height:110%;background-color:white;">

    <div class="challenge-message" style="height:70px;">

      <% sender = @match.sender %>
      <% receiver = @match.receiver %>
      <div class="player-vs-player-div" style="display: flex;margin-top: 20px;justify-content: space-between;align-items: center; width:100%;">
        <div>
          <% if current_user.avatar.attached? %>
            <div>
              <%=  cl_image_tag(current_user.avatar.key, class: "splash-profile-pic") %>
              <%= current_user.name %>
            </div>
          <% else %>
            <div>
              <img src="https://pngimage.net/wp-content/uploads/2018/06/no-avatar-png-8.png" alt="avatar" class="avatar">
              <%= current_user.name %>
            </div>
          <% end %>
        </div>

        <h5 style="position: absolute;left: 46%;">VS</h5>

        <% if current_user.id == sender.id %>
          <div>
            <% if receiver.avatar.attached? %>
              <div>
                <%= receiver.name %>
                <%=  cl_image_tag(receiver.avatar.key, class: "splash-profile-pic") %>
              </div>
            <% else %>
              <div>
                <%= receiver.name %>
                <img src="https://pngimage.net/wp-content/uploads/2018/06/no-avatar-png-8.png" alt="avatar" class="avatar">
              </div>
            <% end %>
          </div>
        <% end %>

        <% if current_user.id == receiver.id %>
          <div>
            <% if sender.avatar.attached? %>
              <div>
                <%= sender.name  %>
                <%=  cl_image_tag(sender.avatar.key, class: "splash-profile-pic") %>
              </div>
            <% else %>
              <div>
                <%= sender.name  %>
                <img src="https://pngimage.net/wp-content/uploads/2018/06/no-avatar-png-8.png" alt="avatar" class="avatar">
              </div>
            <% end %>
          </div>
        <% end %>
      </div>

    </div>

    <div class="message-input-div" style="width:85%" >
      <%= simple_form_for [ current_user, @match, @message ], html: { class: "form-message-input match-chat-form"} do |f| %>
        <%= f.input :content, label: false, placeholder: "Message....", input_html: { class: 'special' }%>
      <% end %>
      <div class="messages-box-container">
        <div id="messages_<%= @match.id %>" class="messagess" data-match-id="<%= @match.id %>" data-user-id="<%= current_user.id%>">
          <div class="message-container">
            <div class="message-name-tag">
              <% sender.name %>
            </div>
            <br>

          </div>
          <% @match.messages.order(created_at: :desc).each do |message| %>

            <% if message.user_id == current_user.id %>
              <div class="message-left">
                <%= render "messages/message", message: message, style: "message-out"%>
              </div>
            <% end %>

            <% if message.user_id != current_user.id %>
              <div class="message-right">
                <%= render "messages/message", message: message, style: "message-in" %>
              </div>
            <% end %>

          <% end %>
        </div>
      </div>
    </div>

  </div>
  <div class="col-3 match-dets" style="background-color:rgba(0,0,0,0.03)">
    <% if !@match.is_complete %>
      <%= render 'challenge' %>
    <% end %>
  </div>
</div>

app/views/matches/show.html.erb
<div class="container">
  <div id="messages" data-match-id="<%= @match.id %>">
    <div class="challenge-message">
      <% sender = @match.sender %>
      <% receiver = @match.receiver %>

      <% if sender.avatar.attached? %>
        <%= cl_image_tag(sender.avatar.key) %>
      <% else %>
        <img src="https://pngimage.net/wp-content/uploads/2018/06/no-avatar-png-8.png" alt="avatar" class="avatar">
      <% end %>

      <h5>VS</h5>

      <% if current_user.id == sender.id %>
        <%= puts "debug" %>
        <%#=  cl_image_tag("receiver.avatar.key") %>
      <% else %>
        <img src="https://pngimage.net/wp-content/uploads/2018/06/no-avatar-png-8.png" alt="avatar" class="avatar">
      <% end %>

      <% if current_user.id == receiver.id %>
        <%#= sender.avatar %>
      <% else %>
        <img src="https://pngimage.net/wp-content/uploads/2018/06/no-avatar-png-8.png" alt="avatar" class="avatar">
      <% end %>

      <%#= @match.content %>

    </div>


    <div class="message-container">  <!-- id="<%= @match.id %>" -->
      <% @match.messages.each do |message| %>
        <%= render "messages/message", message: message %>
      <% end %>
    </div>
  </div>

  <%= simple_form_for [ current_user, @match, @message ] do |f| %>
    <%= f.input :content, label: false, placeholder: "Message" %>
  <% end %>
</div>

app/views/matches/update.html.erb
<h1>Matches#update</h1>
<p>Find me in app/views/matches/update.html.erb</p>